### ISSUE TITLE
真的蛮实用

### ISSUE THREAD

**Issue by heroism6** [FongMi/BearTV#6]
建议tvbox新增视频地址解析库功能    流程统一方式维护解析    并支持自定义  每次启动就拉解析库   如果怕请喝茶聊人生就变相添加此功能  优化解析模式或者智能化判定   换不同接口就不要改代码了

求求了

**Comment by FongMi** [comment]
不會這樣做哦，因為只是個播放殼，不會主動去連伺服器取得資料等。
